import Image, { type StaticImageData } from "next/image";

import chartExplorationImage from "../assets/images/optiq-chart-exploration.png";
import diagramNavigationImage from "../assets/images/optiq-diagram-navigation.png";
import heroImage from "../assets/images/optiq-hero-accessible-learning.png";
import teacherReviewImage from "../assets/images/optiq-teacher-review.png";
import optiqLogo from "../assets/logo.png";

const navigationItems = [
  { href: "#product", label: "Product" },
  { href: "#how-it-works", label: "How it works" },
  { href: "#accessibility", label: "Accessibility" },
  { href: "#examples", label: "Examples" },
] as const;

const productStories = [
  {
    alt: "A learner wearing headphones explores chart information beside a laptop and printed graphs.",
    body: "Exact values in a native table, with keyboard exploration and optional sound.",
    headline: "Every value becomes explorable.",
    id: "charts",
    image: chartExplorationImage,
    label: "Charts",
  },
  {
    alt: "An educator reviews lesson materials, charts, and notes beside a laptop.",
    body: "Review every label, value, relationship, and reading-order choice before export.",
    headline: "Generated by AI. Finalized by people.",
    id: "teacher-review",
    image: teacherReviewImage,
    label: "Educator control",
  },
  {
    alt: "A learner arranges connected process steps while working beside a laptop.",
    body: "Turn connected steps into a clear order students can navigate by keyboard or screen reader.",
    headline: "Relationships stay connected.",
    id: "process-diagrams",
    image: diagramNavigationImage,
    label: "Process diagrams",
  },
] satisfies ReadonlyArray<{
  alt: string;
  body: string;
  headline: string;
  id: string;
  image: StaticImageData;
  label: string;
}>;

function BrandMark() {
  return (
    <span aria-hidden="true" className="brand-logo-window">
      <Image
        alt=""
        className="brand-logo"
        height={1086}
        preload
        sizes="132px"
        src={optiqLogo}
        width={1448}
      />
    </span>
  );
}

function SiteHeader() {
  return (
    <header className="site-header" id="page-top">
      <div className="page-shell header-inner">
        <nav aria-label="Primary navigation" className="desktop-navigation">
          {navigationItems.map((item) => (
            <a href={item.href} key={item.href}>
              {item.label}
            </a>
          ))}
        </nav>

        <a aria-label="Optiq home" className="wordmark" href="#page-top">
          <BrandMark />
        </a>

        <a className="button button-primary header-action" href="#create">
          Create a lesson
        </a>

        <details className="mobile-navigation">
          <summary>Menu</summary>
          <nav aria-label="Mobile navigation">
            {navigationItems.map((item) => (
              <a href={item.href} key={item.href}>
                {item.label}
              </a>
            ))}
            <a className="button button-primary" href="#create">
              Create a lesson
            </a>
          </nav>
        </details>
      </div>
    </header>
  );
}

function EditorialHero() {
  return (
    <>
      <div className="hero-media page-frame">
        <Image
          alt="Two learners work with laptops, headphones, and printed diagrams outdoors at sunset."
          className="hero-image"
          height={829}
          preload
          sizes="(max-width: 768px) calc(100vw - 32px), calc(100vw - 64px)"
          src={heroImage}
          width={1896}
        />
      </div>

      <section
        aria-labelledby="page-title"
        className="editorial-statement section-shell"
      >
        <h1 id="page-title">
          <span>Visual lessons,</span>
          {" "}
          <span className="muted-heading">made accessible.</span>
        </h1>
        <p className="body-large statement-copy">
          Turn charts and process diagrams into lessons students can read, hear,
          and explore.
        </p>
        <div className="button-row">
          <a className="button button-primary" href="#create">
            Create a lesson
          </a>
          <a className="button button-secondary" href="#how-it-works">
            See how it works
          </a>
        </div>
        <p className="quiet-note">AI drafts. Educators decide.</p>
      </section>
    </>
  );
}

function ProductStory({
  alt,
  body,
  headline,
  id,
  image,
  label,
}: (typeof productStories)[number]) {
  return (
    <article className="product-story" id={id}>
      <div className="story-image-frame">
        <Image
          alt={alt}
          className="story-image"
          height={1086}
          sizes="(max-width: 767px) calc(100vw - 48px), (max-width: 1100px) 50vw, 33vw"
          src={image}
          width={1448}
        />
      </div>
      <p className="story-label">{label}</p>
      <h3>{headline}</h3>
      <p>{body}</p>
    </article>
  );
}

function ProductStories() {
  return (
    <section
      aria-labelledby="stories-heading"
      className="product-stories"
      id="product"
    >
      <div className="section-shell">
        <div className="section-introduction stories-introduction">
          <h2 id="stories-heading">
            <span>One visual,</span>
            {" "}
            <span className="muted-heading">more ways to understand.</span>
          </h2>
          <p className="body-large">
            Keep visual information intact. Choose how students explore it.
          </p>
        </div>

        <div className="story-grid" id="examples">
          {productStories.map((story) => (
            <ProductStory key={story.label} {...story} />
          ))}
        </div>
      </div>
    </section>
  );
}

function WorkflowProgress() {
  return (
    <ol aria-label="Lesson creation progress" className="workflow-progress">
      <li aria-current="step">
        <span className="visually-hidden">Current step: </span>
        Source
      </li>
      <li>Review</li>
      <li>Preview</li>
      <li>Export</li>
    </ol>
  );
}

function VisualTypeSelector() {
  return (
    <section aria-labelledby="visual-type-heading" className="visual-type-panel">
      <h3 id="visual-type-heading">Choose a visual</h3>

      <fieldset>
        <legend>Visual type</legend>
        <div className="mode-grid">
          <label className="mode-option">
            <input
              className="visually-hidden"
              defaultChecked
              name="mode"
              type="radio"
              value="chart"
            />
            <span aria-hidden="true" className="selector-check">
              ✓
            </span>
            <span className="mode-copy">
              <span className="mode-title">Chart</span>
              <span className="mode-description">
                Bar or line chart with numeric values.
              </span>
            </span>
          </label>

          <label className="mode-option">
            <input
              className="visually-hidden"
              name="mode"
              type="radio"
              value="process"
            />
            <span aria-hidden="true" className="selector-check">
              ✓
            </span>
            <span className="mode-copy">
              <span className="mode-title">Process diagram</span>
              <span className="mode-description">
                Labelled steps in a meaningful order.
              </span>
            </span>
          </label>
        </div>
      </fieldset>
    </section>
  );
}

function SourceUploader() {
  return (
    <section aria-labelledby="upload-heading" className="upload-panel">
      <div className="upload-heading-row">
        <div>
          <h3 id="upload-heading">Upload one image</h3>
          <p id="upload-help">PNG, JPEG, or WebP · Up to 10 MB</p>
        </div>
      </div>

      <label className="visually-hidden" htmlFor="visual-file">
        Image file
      </label>
      <input
        accept="image/png,image/jpeg,image/webp"
        aria-describedby="upload-help preview-status"
        className="visually-hidden"
        disabled
        id="visual-file"
        type="file"
      />

      <div className="upload-surface">
        <span aria-hidden="true" className="upload-mark">
          +
        </span>
        <strong>Drop it here</strong>
        <span>or choose from your device</span>
        <span className="inactive-file-action">Choose a file</span>
      </div>

      <div className="analysis-actions">
        <button className="button button-primary" disabled type="button">
          Analyze source
        </button>
        <p className="preview-status" id="preview-status">
          <span aria-hidden="true" />
          Preview only — analysis is not connected yet.
        </p>
      </div>
    </section>
  );
}

function LessonCreator() {
  return (
    <section
      aria-labelledby="creator-heading"
      className="lesson-creator"
      id="how-it-works"
    >
      <div className="section-shell">
        <div className="section-introduction creator-introduction">
          <h2 id="creator-heading">From visual to accessible lesson.</h2>
          <p className="body-large">
            Choose, upload, then review the structured draft.
          </p>
        </div>

        <div className="workspace" id="create">
          <div className="workspace-header">
            <WorkflowProgress />
            <span className="environment-label">Preview workspace</span>
          </div>
          <div className="workspace-grid">
            <VisualTypeSelector />
            <SourceUploader />
          </div>
          <div className="workspace-footnotes">
            <p className="review-boundary">
              <strong>Review required before export.</strong> Resolve uncertain
              details first.
            </p>
            <p className="privacy-note" id="privacy">
              When connected, images are sent to OpenAI under applicable API
              data controls. Optiq does not save the upload.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

function AccessibilityPrinciples() {
  return (
    <section
      aria-labelledby="accessibility-heading"
      className="accessibility-principles"
      id="accessibility"
    >
      <div className="section-shell">
        <div className="section-introduction principle-introduction">
          <h2 id="accessibility-heading">
            <span>Accessibility is not</span>
            {" "}
            <span className="muted-heading">a final checkbox.</span>
          </h2>
          <p className="body-large">
            Uncertainty stays visible. Educators stay in control. Students get
            more than a single description.
          </p>
        </div>

        <dl className="principle-list">
          <div>
            <dt>Exact information</dt>
            <dd>
              Values, labels, units, and relationships stay structured.
            </dd>
          </div>
          <div>
            <dt>Teacher control</dt>
            <dd>
              Educators correct the lesson before it is exported.
            </dd>
          </div>
          <div>
            <dt>Multiple ways to explore</dt>
            <dd>
              Use text, tables, keyboard navigation, and optional sound.
            </dd>
          </div>
        </dl>
      </div>
    </section>
  );
}

function FinalCallToAction() {
  return (
    <section aria-labelledby="final-cta-heading" className="final-cta">
      <div className="section-shell">
        <h2 id="final-cta-heading">
          <span>Make every visual</span>
          {" "}
          <span className="muted-heading">part of the lesson.</span>
        </h2>
        <p className="body-large">
          Start with one chart or process diagram.
        </p>
        <div className="button-row">
          <a className="button button-primary" href="#create">
            Create a lesson
          </a>
          <a className="button button-secondary" href="#examples">
            View an example
          </a>
        </div>
      </div>
    </section>
  );
}

function SiteFooter() {
  return (
    <footer className="site-footer">
      <div className="page-shell footer-inner">
        <div className="footer-mission">
          <a aria-label="Optiq home" className="footer-wordmark" href="#page-top">
            optiq
          </a>
          <p>
            Accessible learning experiences from visual educational material.
          </p>
        </div>

        <div className="footer-links">
          <nav aria-labelledby="footer-product-heading">
            <h2 id="footer-product-heading">Product</h2>
            <a href="#how-it-works">How it works</a>
            <a href="#charts">Charts</a>
            <a href="#process-diagrams">Process diagrams</a>
            <a href="#accessibility">Accessibility</a>
          </nav>
          <nav aria-labelledby="footer-resources-heading">
            <h2 id="footer-resources-heading">Explore</h2>
            <a href="#examples">Examples</a>
            <a href="#create">Create a lesson</a>
            <a href="#privacy">Privacy approach</a>
          </nav>
        </div>

        <p className="footer-bottom">
          AI-assisted accessibility, reviewed by educators.
        </p>
      </div>
    </footer>
  );
}

export function AppShell() {
  return (
    <>
      <a className="skip-link" href="#main-content">
        Skip to main content
      </a>
      <SiteHeader />
      <main id="main-content" tabIndex={-1}>
        <EditorialHero />
        <ProductStories />
        <LessonCreator />
        <AccessibilityPrinciples />
        <FinalCallToAction />
      </main>
      <SiteFooter />
    </>
  );
}
