import Image, { type StaticImageData } from "next/image";

import chartExplorationImage from "../assets/images/optiq-chart-exploration.png";
import diagramNavigationImage from "../assets/images/optiq-diagram-navigation.png";
import heroImage from "../assets/images/optiq-hero-accessible-learning.png";
import teacherReviewImage from "../assets/images/optiq-teacher-review.png";

const navigationItems = [
  { href: "#product", label: "Product" },
  { href: "#how-it-works", label: "How it works" },
  { href: "#accessibility", label: "Accessibility" },
  { href: "#examples", label: "Examples" },
] as const;

const productStories = [
  {
    alt: "A learner wearing headphones explores chart information beside a laptop and printed graphs.",
    body: "Students can move through chart data with a keyboard, hear exact values, access a native table, and use optional sonification.",
    headline: "Every value becomes explorable.",
    image: chartExplorationImage,
    label: "Charts",
  },
  {
    alt: "An educator reviews lesson materials, charts, and notes beside a laptop.",
    body: "Teachers review labels, values, relationships, descriptions, and reading order before a lesson is shared.",
    headline: "Generated by AI. Finalized by people.",
    image: teacherReviewImage,
    label: "Educator control",
  },
  {
    alt: "A learner arranges connected process steps while working beside a laptop.",
    body: "Optiq turns visual processes into ordered steps and navigable relationships without flattening the entire diagram into one paragraph.",
    headline: "Relationships stay connected.",
    image: diagramNavigationImage,
    label: "Process diagrams",
  },
] satisfies ReadonlyArray<{
  alt: string;
  body: string;
  headline: string;
  image: StaticImageData;
  label: string;
}>;

function SiteHeader() {
  return (
    <header className="site-header" id="page-top">
      <div className="page-shell header-inner">
        <nav aria-label="Primary navigation" className="desktop-navigation">
          {navigationItems.map((item) => (
            <a href={item.href} key={item.href}>
              {item.label}
            </a>
          ))}
        </nav>

        <a aria-label="Optiq home" className="wordmark" href="#page-top">
          optiq
        </a>

        <a className="button button-primary header-action" href="#create">
          Create a lesson
        </a>

        <details className="mobile-navigation">
          <summary>Menu</summary>
          <nav aria-label="Mobile navigation">
            {navigationItems.map((item) => (
              <a href={item.href} key={item.href}>
                {item.label}
              </a>
            ))}
            <a className="button button-primary" href="#create">
              Create a lesson
            </a>
          </nav>
        </details>
      </div>
    </header>
  );
}

function EditorialHero() {
  return (
    <>
      <div className="hero-media page-frame">
        <Image
          alt="Two learners work with laptops, headphones, and printed diagrams outdoors at sunset."
          className="hero-image"
          height={829}
          preload
          sizes="(max-width: 768px) calc(100vw - 32px), calc(100vw - 64px)"
          src={heroImage}
          width={1896}
        />
      </div>

      <section
        aria-labelledby="page-title"
        className="editorial-statement section-shell"
        id="product"
      >
        <h1 id="page-title">
          <span>Visual lessons,</span>
          {" "}
          <span className="muted-heading">made accessible.</span>
        </h1>
        <p className="body-large statement-copy">
          Turn charts and process diagrams into structured experiences students
          can read, navigate, hear, and explore.
        </p>
        <div className="button-row">
          <a className="button button-primary" href="#create">
            Create a lesson
          </a>
          <a className="button button-secondary" href="#how-it-works">
            See how it works
          </a>
        </div>
        <p className="quiet-note">
          AI-assisted accessibility, reviewed and corrected by educators.
        </p>
      </section>
    </>
  );
}

function ProductStory({
  alt,
  body,
  headline,
  image,
  label,
}: (typeof productStories)[number]) {
  return (
    <article className="product-story">
      <div className="story-image-frame">
        <Image
          alt={alt}
          className="story-image"
          height={1086}
          sizes="(max-width: 767px) calc(100vw - 48px), (max-width: 1100px) 50vw, 33vw"
          src={image}
          width={1448}
        />
      </div>
      <p className="story-label">{label}</p>
      <h3>{headline}</h3>
      <p>{body}</p>
    </article>
  );
}

function ProductStories() {
  return (
    <section
      aria-labelledby="stories-heading"
      className="product-stories"
      id="examples"
    >
      <div className="section-shell">
        <div className="section-introduction stories-introduction">
          <h2 id="stories-heading">
            <span>One visual,</span>
            {" "}
            <span className="muted-heading">more ways to understand.</span>
          </h2>
          <p className="body-large">
            Optiq preserves the information inside visual lessons and gives
            educators control over how students experience it.
          </p>
        </div>

        <div className="story-grid">
          {productStories.map((story) => (
            <ProductStory key={story.label} {...story} />
          ))}
        </div>
      </div>
    </section>
  );
}

function WorkflowProgress() {
  return (
    <ol aria-label="Lesson creation progress" className="workflow-progress">
      <li aria-current="step">
        <span aria-hidden="true" />
        Source
      </li>
      <li>
        <span aria-hidden="true" />
        Review
      </li>
      <li>
        <span aria-hidden="true" />
        Preview
      </li>
      <li>
        <span aria-hidden="true" />
        Export
      </li>
    </ol>
  );
}

function VisualTypeSelector() {
  return (
    <section aria-labelledby="visual-type-heading" className="visual-type-panel">
      <h3 id="visual-type-heading">Choose the visual type</h3>
      <p id="visual-type-help">
        Select the format that best matches one clear visual.
      </p>

      <fieldset aria-describedby="visual-type-help">
        <legend>Visual type</legend>
        <div className="mode-grid">
          <label className="mode-option">
            <input
              className="visually-hidden"
              defaultChecked
              name="mode"
              type="radio"
              value="chart"
            />
            <span aria-hidden="true" className="selector-check">
              ✓
            </span>
            <span className="mode-copy">
              <span className="mode-title">Chart</span>
              <span className="mode-description">
                Bar or line chart with labelled numeric values.
              </span>
              <span className="mode-output">
                Data table · Keyboard exploration · Optional sound
              </span>
            </span>
          </label>

          <label className="mode-option">
            <input
              className="visually-hidden"
              name="mode"
              type="radio"
              value="process"
            />
            <span aria-hidden="true" className="selector-check">
              ✓
            </span>
            <span className="mode-copy">
              <span className="mode-title">Process diagram</span>
              <span className="mode-description">
                Labelled steps connected in a meaningful order.
              </span>
              <span className="mode-output">
                Steps · Relationships · Navigation order
              </span>
            </span>
          </label>
        </div>
      </fieldset>
    </section>
  );
}

function SourceUploader() {
  return (
    <section aria-labelledby="upload-heading" className="upload-panel">
      <div className="upload-heading-row">
        <div>
          <h3 id="upload-heading">Add one clear image</h3>
          <p id="upload-help">PNG, JPEG, or WebP · Up to 10 MB</p>
        </div>
        <span className="environment-label">Static preview</span>
      </div>

      <label className="visually-hidden" htmlFor="visual-file">
        Image file
      </label>
      <input
        accept="image/png,image/jpeg,image/webp"
        aria-describedby="upload-help preview-status upload-requirement"
        className="visually-hidden"
        disabled
        id="visual-file"
        type="file"
      />

      <div className="upload-surface">
        <span aria-hidden="true" className="upload-mark">
          +
        </span>
        <strong>Drop an image here</strong>
        <span>or choose a file</span>
        <span className="inactive-file-action">Choose a file</span>
      </div>

      <div className="analysis-actions">
        <button className="button button-primary" disabled type="button">
          Analyze source
        </button>
        <p className="preview-status" id="preview-status">
          <span aria-hidden="true" />
          Analysis is unavailable in this static preview.
        </p>
      </div>
      <p className="upload-requirement" id="upload-requirement">
        Add a valid image to continue when live analysis is connected.
      </p>
    </section>
  );
}

function LessonCreator() {
  return (
    <section
      aria-labelledby="creator-heading"
      className="lesson-creator"
      id="how-it-works"
    >
      <div className="section-shell">
        <div className="section-introduction creator-introduction" id="create">
          <h2 id="creator-heading">Create an accessible lesson</h2>
          <p className="body-large">
            Upload one clear chart or process diagram. Optiq will build a
            structured draft for teacher review.
          </p>
        </div>

        <div className="workspace">
          <WorkflowProgress />
          <div className="workspace-grid">
            <VisualTypeSelector />
            <SourceUploader />
          </div>
          <div className="workspace-footnotes">
            <p className="review-boundary">
              <strong>Teacher review is required.</strong> Critical uncertainties
              must be resolved before a standalone lesson can be exported.
            </p>
            <p className="privacy-note" id="privacy">
              When live analysis is connected, the selected image will be sent
              to OpenAI under the applicable API data controls. The core flow
              requires no account and does not save the upload.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

function AccessibilityPrinciples() {
  return (
    <section
      aria-labelledby="accessibility-heading"
      className="accessibility-principles"
      id="accessibility"
    >
      <div className="section-shell">
        <div className="section-introduction principle-introduction">
          <h2 id="accessibility-heading">
            <span>Accessibility is not</span>
            {" "}
            <span className="muted-heading">a final checkbox.</span>
          </h2>
          <p className="body-large">
            Optiq keeps educators involved where interpretation matters. Unknown
            information remains visible, generated content remains editable,
            and students receive more than a single description.
          </p>
        </div>

        <dl className="principle-list">
          <div>
            <dt>Exact information</dt>
            <dd>
              Values, labels, units, and relationships remain available in
              structured form.
            </dd>
          </div>
          <div>
            <dt>Teacher control</dt>
            <dd>
              Educators review and correct the generated lesson before it is
              exported.
            </dd>
          </div>
          <div>
            <dt>Multiple ways to explore</dt>
            <dd>
              Students can use text, tables, keyboard navigation, and optional
              sound.
            </dd>
          </div>
        </dl>
      </div>
    </section>
  );
}

function FinalCallToAction() {
  return (
    <section aria-labelledby="final-cta-heading" className="final-cta">
      <div className="section-shell">
        <h2 id="final-cta-heading">
          <span>Make every visual</span>
          {" "}
          <span className="muted-heading">part of the lesson.</span>
        </h2>
        <p className="body-large">
          Create an accessible experience from a chart or process diagram.
        </p>
        <div className="button-row">
          <a className="button button-primary" href="#create">
            Create a lesson
          </a>
          <a className="button button-secondary" href="#examples">
            View an example
          </a>
        </div>
      </div>
    </section>
  );
}

function SiteFooter() {
  return (
    <footer className="site-footer">
      <div className="page-shell footer-inner">
        <div className="footer-mission">
          <a aria-label="Optiq home" className="footer-wordmark" href="#page-top">
            optiq
          </a>
          <p>
            Accessible learning experiences from visual educational material.
          </p>
        </div>

        <div className="footer-links">
          <nav aria-labelledby="footer-product-heading">
            <h2 id="footer-product-heading">Product</h2>
            <a href="#how-it-works">How it works</a>
            <a href="#examples">Charts</a>
            <a href="#examples">Process diagrams</a>
            <a href="#accessibility">Accessibility</a>
          </nav>
          <nav aria-labelledby="footer-resources-heading">
            <h2 id="footer-resources-heading">Explore</h2>
            <a href="#examples">Examples</a>
            <a href="#create">Create a lesson</a>
            <a href="#privacy">Privacy approach</a>
          </nav>
        </div>

        <p className="footer-bottom">
          AI-assisted accessibility, reviewed by educators.
        </p>
      </div>
    </footer>
  );
}

export function AppShell() {
  return (
    <>
      <a className="skip-link" href="#main-content">
        Skip to main content
      </a>
      <SiteHeader />
      <main id="main-content" tabIndex={-1}>
        <EditorialHero />
        <ProductStories />
        <LessonCreator />
        <AccessibilityPrinciples />
        <FinalCallToAction />
      </main>
      <SiteFooter />
    </>
  );
}
